version: "3.9"
services:

  database:
    image: postgres:14.0
    working_dir: /app
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    depends_on:
      - php-fpm
    volumes:
      - /data/db/postgres/:/var/lib/postgresql/data/
    networks:
      dataprag:
        aliases:
          - "db.dataprag"

  webserver:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    networks:
      dataprag:

  php-fpm:
    build: ./docker/php-fpm
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      dataprag:

volumes:
  database:

networks:
  dataprag:
